[package]
edition.workspace = true
license.workspace = true
name = "kraai-workspace-fs"
publish = false
rust-version.workspace = true
version = "0.1.0"

[dependencies]
kraai-io.workspace = true
thiserror.workspace = true

[dev-dependencies]
ulid.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dev-dependencies]
nix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
] }
