[package]
edition.workspace = true
license.workspace = true
name = "kraai-workspace-fs"
publish = false
rust-version.workspace = true
version = "0.1.0"

[dependencies]
thiserror.workspace = true
ulid.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Wdk_Foundation",
  "Wdk_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
] }
