[package]
edition.workspace = true
license.workspace = true
name = "kraai-io"
publish = false
rust-version.workspace = true
version = "0.1.0"

[features]
async = ["dep:tokio"]
default = []
http = ["async", "dep:http", "dep:reqwest"]

[dependencies]
http = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, optional = true }
ulid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Wdk_Foundation",
  "Wdk_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
] }
