[package]
edition.workspace = true
license.workspace = true
name = "kraai-command-web-search"
publish = false
rust-version.workspace = true
version = "0.1.0"

[dependencies]
kraai-command-catalog.workspace = true
kraai-command-core.workspace = true
kraai-types.workspace = true
nu-engine.workspace = true
nu-protocol.workspace = true
