identifier = "com.agent"

[build]
before-build-command = "cd ./../frontend/ && bun run build"
before-dev-command = "cd ./frontend/ && bun run dev"
dev-url = "http://localhost:1420"
frontend-dist = "./frontend/dist"

[bundle]
active = true
icon = [
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/32x32.png",
  "icons/icon.icns",
  "icons/icon.ico",
]

[[app.windows]]
title = "MyApp"

[plugins.updater]
active = true
dialog = true
endpoints = [
  "https://github.com/ominit/agent/releases/latest/download/latest.json",
]
pubkey = "updater pub key"
