name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - run: nix develop --command cargo autoinherit
      - run: nix develop --command just generate-cargo-nix
      - run: nix fmt
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
