name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      - run: nix fmt
      - run: nix develop --command cargo hakari generate
      - run: nix develop --command cargo hakari manage-deps
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
